
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMENT ELSE GUI HOTKEY HOTSTRING IDENT IF LBRACE LOOP MSGBOX NEWLINE NUMBER RBRACE RETURN RUN SEND STRINGscript : lineslines : line\n             | lines lineline : HOTSTRING STRING NEWLINE\n            | HOTKEY SEND STRING NEWLINE\n            | HOTKEY RUN STRING NEWLINE\n            | HOTKEY NEWLINE\n            | IF condition NEWLINE\n            | ELSE NEWLINE\n            | LOOP NEWLINE\n            | GUI NEWLINE\n            | NEWLINE\n            | IDENT NEWLINE\n            | STRING NEWLINEcondition : IDENT\n                 | IDENT NUMBER'
    
_lr_action_items = {'HOTSTRING':([0,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[4,4,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'HOTKEY':([0,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[7,7,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'IF':([0,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[8,8,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'ELSE':([0,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[9,9,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'LOOP':([0,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[10,10,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'GUI':([0,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[11,11,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'NEWLINE':([0,2,3,5,6,7,9,10,11,12,13,14,15,17,19,20,21,22,23,24,25,26,27,28,29,30,31,],[6,6,-2,15,-12,17,21,22,23,24,-3,25,-14,-7,28,-15,-9,-10,-11,-13,-4,30,31,-8,-16,-5,-6,]),'IDENT':([0,2,3,6,8,13,15,17,21,22,23,24,25,28,30,31,],[12,12,-2,-12,20,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'STRING':([0,2,3,4,6,13,15,16,17,18,21,22,23,24,25,28,30,31,],[5,5,-2,14,-12,-3,-14,26,-7,27,-9,-10,-11,-13,-4,-8,-5,-6,]),'$end':([1,2,3,6,13,15,17,21,22,23,24,25,28,30,31,],[0,-1,-2,-12,-3,-14,-7,-9,-10,-11,-13,-4,-8,-5,-6,]),'SEND':([7,],[16,]),'RUN':([7,],[18,]),'NUMBER':([20,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'script':([0,],[1,]),'lines':([0,],[2,]),'line':([0,2,],[3,13,]),'condition':([8,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> script","S'",1,None,None,None),
  ('script -> lines','script',1,'p_script','AHK_Validator.py',75),
  ('lines -> line','lines',1,'p_lines','AHK_Validator.py',79),
  ('lines -> lines line','lines',2,'p_lines','AHK_Validator.py',80),
  ('line -> HOTSTRING STRING NEWLINE','line',3,'p_line','AHK_Validator.py',84),
  ('line -> HOTKEY SEND STRING NEWLINE','line',4,'p_line','AHK_Validator.py',85),
  ('line -> HOTKEY RUN STRING NEWLINE','line',4,'p_line','AHK_Validator.py',86),
  ('line -> HOTKEY NEWLINE','line',2,'p_line','AHK_Validator.py',87),
  ('line -> IF condition NEWLINE','line',3,'p_line','AHK_Validator.py',88),
  ('line -> ELSE NEWLINE','line',2,'p_line','AHK_Validator.py',89),
  ('line -> LOOP NEWLINE','line',2,'p_line','AHK_Validator.py',90),
  ('line -> GUI NEWLINE','line',2,'p_line','AHK_Validator.py',91),
  ('line -> NEWLINE','line',1,'p_line','AHK_Validator.py',92),
  ('line -> IDENT NEWLINE','line',2,'p_line','AHK_Validator.py',93),
  ('line -> STRING NEWLINE','line',2,'p_line','AHK_Validator.py',94),
  ('condition -> IDENT','condition',1,'p_condition','AHK_Validator.py',98),
  ('condition -> IDENT NUMBER','condition',2,'p_condition','AHK_Validator.py',99),
]
